//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Monitor.EntityModels
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class EntityContext : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект EntityContext, используя строку соединения из раздела "EntityContext" файла конфигурации приложения.
        /// </summary>
        public EntityContext() : base("name=EntityContext", "EntityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта EntityContext.
        /// </summary>
        public EntityContext(string connectionString) : base(connectionString, "EntityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта EntityContext.
        /// </summary>
        public EntityContext(EntityConnection connection) : base(connection, "EntityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<kom> kom
        {
            get
            {
                if ((_kom == null))
                {
                    _kom = base.CreateObjectSet<kom>("kom");
                }
                return _kom;
            }
        }
        private ObjectSet<kom> _kom;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet kom. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTokom(kom kom)
        {
            base.AddObject("kom", kom);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FormModel", Name="kom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kom : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта kom.
        /// </summary>
        /// <param name="id">Исходное значение свойства ID.</param>
        /// <param name="sYST">Исходное значение свойства SYST.</param>
        /// <param name="fL_DISPLAY">Исходное значение свойства FL_DISPLAY.</param>
        public static kom Createkom(global::System.Int32 id, global::System.Int16 sYST, global::System.Int32 fL_DISPLAY)
        {
            kom kom = new kom();
            kom.ID = id;
            kom.SYST = sYST;
            kom.FL_DISPLAY = fL_DISPLAY;
            return kom;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String N_KOM
        {
            get
            {
                return _N_KOM;
            }
            set
            {
                OnN_KOMChanging(value);
                ReportPropertyChanging("N_KOM");
                _N_KOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("N_KOM");
                OnN_KOMChanged();
            }
        }
        private global::System.String _N_KOM;
        partial void OnN_KOMChanging(global::System.String value);
        partial void OnN_KOMChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String V_VS
        {
            get
            {
                return _V_VS;
            }
            set
            {
                OnV_VSChanging(value);
                ReportPropertyChanging("V_VS");
                _V_VS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("V_VS");
                OnV_VSChanged();
            }
        }
        private global::System.String _V_VS;
        partial void OnV_VSChanging(global::System.String value);
        partial void OnV_VSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String N_E
        {
            get
            {
                return _N_E;
            }
            set
            {
                OnN_EChanging(value);
                ReportPropertyChanging("N_E");
                _N_E = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("N_E");
                OnN_EChanged();
            }
        }
        private global::System.String _N_E;
        partial void OnN_EChanging(global::System.String value);
        partial void OnN_EChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ST
        {
            get
            {
                return _ST;
            }
            set
            {
                OnSTChanging(value);
                ReportPropertyChanging("ST");
                _ST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ST");
                OnSTChanged();
            }
        }
        private global::System.String _ST;
        partial void OnSTChanging(global::System.String value);
        partial void OnSTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String V_CH
        {
            get
            {
                return _V_CH;
            }
            set
            {
                OnV_CHChanging(value);
                ReportPropertyChanging("V_CH");
                _V_CH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("V_CH");
                OnV_CHChanged();
            }
        }
        private global::System.String _V_CH;
        partial void OnV_CHChanging(global::System.String value);
        partial void OnV_CHChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REZH_KOM
        {
            get
            {
                return _REZH_KOM;
            }
            set
            {
                OnREZH_KOMChanging(value);
                ReportPropertyChanging("REZH_KOM");
                _REZH_KOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REZH_KOM");
                OnREZH_KOMChanged();
            }
        }
        private global::System.String _REZH_KOM;
        partial void OnREZH_KOMChanging(global::System.String value);
        partial void OnREZH_KOMChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D_OTPR
        {
            get
            {
                return _D_OTPR;
            }
            set
            {
                OnD_OTPRChanging(value);
                ReportPropertyChanging("D_OTPR");
                _D_OTPR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D_OTPR");
                OnD_OTPRChanged();
            }
        }
        private Nullable<global::System.DateTime> _D_OTPR;
        partial void OnD_OTPRChanging(Nullable<global::System.DateTime> value);
        partial void OnD_OTPRChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String V_SHET
        {
            get
            {
                return _V_SHET;
            }
            set
            {
                OnV_SHETChanging(value);
                ReportPropertyChanging("V_SHET");
                _V_SHET = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("V_SHET");
                OnV_SHETChanged();
            }
        }
        private global::System.String _V_SHET;
        partial void OnV_SHETChanging(global::System.String value);
        partial void OnV_SHETChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VSEGO
        {
            get
            {
                return _VSEGO;
            }
            set
            {
                OnVSEGOChanging(value);
                ReportPropertyChanging("VSEGO");
                _VSEGO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VSEGO");
                OnVSEGOChanged();
            }
        }
        private Nullable<global::System.Int32> _VSEGO;
        partial void OnVSEGOChanging(Nullable<global::System.Int32> value);
        partial void OnVSEGOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VA
        {
            get
            {
                return _VA;
            }
            set
            {
                OnVAChanging(value);
                ReportPropertyChanging("VA");
                _VA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VA");
                OnVAChanged();
            }
        }
        private Nullable<global::System.Int32> _VA;
        partial void OnVAChanging(Nullable<global::System.Int32> value);
        partial void OnVAChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MTLB
        {
            get
            {
                return _MTLB;
            }
            set
            {
                OnMTLBChanging(value);
                ReportPropertyChanging("MTLB");
                _MTLB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MTLB");
                OnMTLBChanged();
            }
        }
        private Nullable<global::System.Int32> _MTLB;
        partial void OnMTLBChanging(Nullable<global::System.Int32> value);
        partial void OnMTLBChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SUD
        {
            get
            {
                return _SUD;
            }
            set
            {
                OnSUDChanging(value);
                ReportPropertyChanging("SUD");
                _SUD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SUD");
                OnSUDChanged();
            }
        }
        private Nullable<global::System.Int32> _SUD;
        partial void OnSUDChanging(Nullable<global::System.Int32> value);
        partial void OnSUDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Z_PREDS
        {
            get
            {
                return _Z_PREDS;
            }
            set
            {
                OnZ_PREDSChanging(value);
                ReportPropertyChanging("Z_PREDS");
                _Z_PREDS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Z_PREDS");
                OnZ_PREDSChanged();
            }
        }
        private global::System.String _Z_PREDS;
        partial void OnZ_PREDSChanging(global::System.String value);
        partial void OnZ_PREDSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PREDS
        {
            get
            {
                return _PREDS;
            }
            set
            {
                OnPREDSChanging(value);
                ReportPropertyChanging("PREDS");
                _PREDS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PREDS");
                OnPREDSChanged();
            }
        }
        private global::System.String _PREDS;
        partial void OnPREDSChanging(global::System.String value);
        partial void OnPREDSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String S_UD
        {
            get
            {
                return _S_UD;
            }
            set
            {
                OnS_UDChanging(value);
                ReportPropertyChanging("S_UD");
                _S_UD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("S_UD");
                OnS_UDChanged();
            }
        }
        private global::System.String _S_UD;
        partial void OnS_UDChanging(global::System.String value);
        partial void OnS_UDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String N_UD
        {
            get
            {
                return _N_UD;
            }
            set
            {
                OnN_UDChanging(value);
                ReportPropertyChanging("N_UD");
                _N_UD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("N_UD");
                OnN_UDChanged();
            }
        }
        private global::System.String _N_UD;
        partial void OnN_UDChanging(global::System.String value);
        partial void OnN_UDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VIDAN
        {
            get
            {
                return _VIDAN;
            }
            set
            {
                OnVIDANChanging(value);
                ReportPropertyChanging("VIDAN");
                _VIDAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VIDAN");
                OnVIDANChanged();
            }
        }
        private global::System.String _VIDAN;
        partial void OnVIDANChanging(global::System.String value);
        partial void OnVIDANChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D_VID
        {
            get
            {
                return _D_VID;
            }
            set
            {
                OnD_VIDChanging(value);
                ReportPropertyChanging("D_VID");
                _D_VID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D_VID");
                OnD_VIDChanged();
            }
        }
        private Nullable<global::System.DateTime> _D_VID;
        partial void OnD_VIDChanging(Nullable<global::System.DateTime> value);
        partial void OnD_VIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRIM
        {
            get
            {
                return _PRIM;
            }
            set
            {
                OnPRIMChanging(value);
                ReportPropertyChanging("PRIM");
                _PRIM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRIM");
                OnPRIMChanged();
            }
        }
        private global::System.String _PRIM;
        partial void OnPRIMChanging(global::System.String value);
        partial void OnPRIMChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SPEC
        {
            get
            {
                return _SPEC;
            }
            set
            {
                OnSPECChanging(value);
                ReportPropertyChanging("SPEC");
                _SPEC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SPEC");
                OnSPECChanged();
            }
        }
        private global::System.String _SPEC;
        partial void OnSPECChanging(global::System.String value);
        partial void OnSPECChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VUS1
        {
            get
            {
                return _VUS1;
            }
            set
            {
                OnVUS1Changing(value);
                ReportPropertyChanging("VUS1");
                _VUS1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VUS1");
                OnVUS1Changed();
            }
        }
        private global::System.String _VUS1;
        partial void OnVUS1Changing(global::System.String value);
        partial void OnVUS1Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VUS2
        {
            get
            {
                return _VUS2;
            }
            set
            {
                OnVUS2Changing(value);
                ReportPropertyChanging("VUS2");
                _VUS2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VUS2");
                OnVUS2Changed();
            }
        }
        private global::System.String _VUS2;
        partial void OnVUS2Changing(global::System.String value);
        partial void OnVUS2Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VUS3
        {
            get
            {
                return _VUS3;
            }
            set
            {
                OnVUS3Changing(value);
                ReportPropertyChanging("VUS3");
                _VUS3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VUS3");
                OnVUS3Changed();
            }
        }
        private global::System.String _VUS3;
        partial void OnVUS3Changing(global::System.String value);
        partial void OnVUS3Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PR
        {
            get
            {
                return _PR;
            }
            set
            {
                OnPRChanging(value);
                ReportPropertyChanging("PR");
                _PR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PR");
                OnPRChanged();
            }
        }
        private Nullable<global::System.Int32> _PR;
        partial void OnPRChanging(Nullable<global::System.Int32> value);
        partial void OnPRChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D_PR
        {
            get
            {
                return _D_PR;
            }
            set
            {
                OnD_PRChanging(value);
                ReportPropertyChanging("D_PR");
                _D_PR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D_PR");
                OnD_PRChanged();
            }
        }
        private Nullable<global::System.DateTime> _D_PR;
        partial void OnD_PRChanging(Nullable<global::System.DateTime> value);
        partial void OnD_PRChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RAILROAD
        {
            get
            {
                return _RAILROAD;
            }
            set
            {
                OnRAILROADChanging(value);
                ReportPropertyChanging("RAILROAD");
                _RAILROAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RAILROAD");
                OnRAILROADChanged();
            }
        }
        private global::System.String _RAILROAD;
        partial void OnRAILROADChanging(global::System.String value);
        partial void OnRAILROADChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String V_OKRUG
        {
            get
            {
                return _V_OKRUG;
            }
            set
            {
                OnV_OKRUGChanging(value);
                ReportPropertyChanging("V_OKRUG");
                _V_OKRUG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("V_OKRUG");
                OnV_OKRUGChanged();
            }
        }
        private global::System.String _V_OKRUG;
        partial void OnV_OKRUGChanging(global::System.String value);
        partial void OnV_OKRUGChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FL_UB
        {
            get
            {
                return _FL_UB;
            }
            set
            {
                OnFL_UBChanging(value);
                ReportPropertyChanging("FL_UB");
                _FL_UB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FL_UB");
                OnFL_UBChanged();
            }
        }
        private Nullable<global::System.Int32> _FL_UB;
        partial void OnFL_UBChanging(Nullable<global::System.Int32> value);
        partial void OnFL_UBChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FL_PEREOD
        {
            get
            {
                return _FL_PEREOD;
            }
            set
            {
                OnFL_PEREODChanging(value);
                ReportPropertyChanging("FL_PEREOD");
                _FL_PEREOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FL_PEREOD");
                OnFL_PEREODChanged();
            }
        }
        private Nullable<global::System.Int32> _FL_PEREOD;
        partial void OnFL_PEREODChanging(Nullable<global::System.Int32> value);
        partial void OnFL_PEREODChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NARAD
        {
            get
            {
                return _NARAD;
            }
            set
            {
                OnNARADChanging(value);
                ReportPropertyChanging("NARAD");
                _NARAD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NARAD");
                OnNARADChanged();
            }
        }
        private Nullable<global::System.Int32> _NARAD;
        partial void OnNARADChanging(Nullable<global::System.Int32> value);
        partial void OnNARADChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GOROD
        {
            get
            {
                return _GOROD;
            }
            set
            {
                OnGORODChanging(value);
                ReportPropertyChanging("GOROD");
                _GOROD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GOROD");
                OnGORODChanged();
            }
        }
        private global::System.String _GOROD;
        partial void OnGORODChanging(global::System.String value);
        partial void OnGORODChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STREET
        {
            get
            {
                return _STREET;
            }
            set
            {
                OnSTREETChanging(value);
                ReportPropertyChanging("STREET");
                _STREET = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STREET");
                OnSTREETChanged();
            }
        }
        private global::System.String _STREET;
        partial void OnSTREETChanging(global::System.String value);
        partial void OnSTREETChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIP
        {
            get
            {
                return _ZIP;
            }
            set
            {
                OnZIPChanging(value);
                ReportPropertyChanging("ZIP");
                _ZIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIP");
                OnZIPChanged();
            }
        }
        private global::System.String _ZIP;
        partial void OnZIPChanging(global::System.String value);
        partial void OnZIPChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ISSIBVO
        {
            get
            {
                return _ISSIBVO;
            }
            set
            {
                OnISSIBVOChanging(value);
                ReportPropertyChanging("ISSIBVO");
                _ISSIBVO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISSIBVO");
                OnISSIBVOChanged();
            }
        }
        private Nullable<global::System.Int32> _ISSIBVO;
        partial void OnISSIBVOChanging(Nullable<global::System.Int32> value);
        partial void OnISSIBVOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DOLJNOST
        {
            get
            {
                return _DOLJNOST;
            }
            set
            {
                OnDOLJNOSTChanging(value);
                ReportPropertyChanging("DOLJNOST");
                _DOLJNOST = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DOLJNOST");
                OnDOLJNOSTChanged();
            }
        }
        private global::System.String _DOLJNOST;
        partial void OnDOLJNOSTChanging(global::System.String value);
        partial void OnDOLJNOSTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> FOLLOW_OFICER
        {
            get
            {
                return _FOLLOW_OFICER;
            }
            set
            {
                OnFOLLOW_OFICERChanging(value);
                ReportPropertyChanging("FOLLOW_OFICER");
                _FOLLOW_OFICER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FOLLOW_OFICER");
                OnFOLLOW_OFICERChanged();
            }
        }
        private Nullable<global::System.Int16> _FOLLOW_OFICER;
        partial void OnFOLLOW_OFICERChanging(Nullable<global::System.Int16> value);
        partial void OnFOLLOW_OFICERChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> FOLLOW_PRAPOR
        {
            get
            {
                return _FOLLOW_PRAPOR;
            }
            set
            {
                OnFOLLOW_PRAPORChanging(value);
                ReportPropertyChanging("FOLLOW_PRAPOR");
                _FOLLOW_PRAPOR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FOLLOW_PRAPOR");
                OnFOLLOW_PRAPORChanged();
            }
        }
        private Nullable<global::System.Int16> _FOLLOW_PRAPOR;
        partial void OnFOLLOW_PRAPORChanging(Nullable<global::System.Int16> value);
        partial void OnFOLLOW_PRAPORChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> FOLLOW_SOLDERS
        {
            get
            {
                return _FOLLOW_SOLDERS;
            }
            set
            {
                OnFOLLOW_SOLDERSChanging(value);
                ReportPropertyChanging("FOLLOW_SOLDERS");
                _FOLLOW_SOLDERS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FOLLOW_SOLDERS");
                OnFOLLOW_SOLDERSChanged();
            }
        }
        private Nullable<global::System.Int16> _FOLLOW_SOLDERS;
        partial void OnFOLLOW_SOLDERSChanging(Nullable<global::System.Int16> value);
        partial void OnFOLLOW_SOLDERSChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NVESHAT
        {
            get
            {
                return _NVESHAT;
            }
            set
            {
                OnNVESHATChanging(value);
                ReportPropertyChanging("NVESHAT");
                _NVESHAT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NVESHAT");
                OnNVESHATChanged();
            }
        }
        private global::System.String _NVESHAT;
        partial void OnNVESHATChanging(global::System.String value);
        partial void OnNVESHATChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DVESHAT
        {
            get
            {
                return _DVESHAT;
            }
            set
            {
                OnDVESHATChanging(value);
                ReportPropertyChanging("DVESHAT");
                _DVESHAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DVESHAT");
                OnDVESHATChanged();
            }
        }
        private Nullable<global::System.DateTime> _DVESHAT;
        partial void OnDVESHATChanging(Nullable<global::System.DateTime> value);
        partial void OnDVESHATChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> KOLSUHPAY
        {
            get
            {
                return _KOLSUHPAY;
            }
            set
            {
                OnKOLSUHPAYChanging(value);
                ReportPropertyChanging("KOLSUHPAY");
                _KOLSUHPAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KOLSUHPAY");
                OnKOLSUHPAYChanged();
            }
        }
        private Nullable<global::System.Int16> _KOLSUHPAY;
        partial void OnKOLSUHPAYChanging(Nullable<global::System.Int16> value);
        partial void OnKOLSUHPAYChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SYST
        {
            get
            {
                return _SYST;
            }
            set
            {
                OnSYSTChanging(value);
                ReportPropertyChanging("SYST");
                _SYST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SYST");
                OnSYSTChanged();
            }
        }
        private global::System.Int16 _SYST;
        partial void OnSYSTChanging(global::System.Int16 value);
        partial void OnSYSTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POEZD
        {
            get
            {
                return _POEZD;
            }
            set
            {
                OnPOEZDChanging(value);
                ReportPropertyChanging("POEZD");
                _POEZD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POEZD");
                OnPOEZDChanged();
            }
        }
        private global::System.String _POEZD;
        partial void OnPOEZDChanging(global::System.String value);
        partial void OnPOEZDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VID_TR
        {
            get
            {
                return _VID_TR;
            }
            set
            {
                OnVID_TRChanging(value);
                ReportPropertyChanging("VID_TR");
                _VID_TR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VID_TR");
                OnVID_TRChanged();
            }
        }
        private global::System.String _VID_TR;
        partial void OnVID_TRChanging(global::System.String value);
        partial void OnVID_TRChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String T_OTPR
        {
            get
            {
                return _T_OTPR;
            }
            set
            {
                OnT_OTPRChanging(value);
                ReportPropertyChanging("T_OTPR");
                _T_OTPR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("T_OTPR");
                OnT_OTPRChanged();
            }
        }
        private global::System.String _T_OTPR;
        partial void OnT_OTPRChanging(global::System.String value);
        partial void OnT_OTPRChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String N_DOV
        {
            get
            {
                return _N_DOV;
            }
            set
            {
                OnN_DOVChanging(value);
                ReportPropertyChanging("N_DOV");
                _N_DOV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("N_DOV");
                OnN_DOVChanged();
            }
        }
        private global::System.String _N_DOV;
        partial void OnN_DOVChanging(global::System.String value);
        partial void OnN_DOVChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> D_DOV
        {
            get
            {
                return _D_DOV;
            }
            set
            {
                OnD_DOVChanging(value);
                ReportPropertyChanging("D_DOV");
                _D_DOV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D_DOV");
                OnD_DOVChanged();
            }
        }
        private Nullable<global::System.DateTime> _D_DOV;
        partial void OnD_DOVChanging(Nullable<global::System.DateTime> value);
        partial void OnD_DOVChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FL_DISPLAY
        {
            get
            {
                return _FL_DISPLAY;
            }
            set
            {
                OnFL_DISPLAYChanging(value);
                ReportPropertyChanging("FL_DISPLAY");
                _FL_DISPLAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FL_DISPLAY");
                OnFL_DISPLAYChanged();
            }
        }
        private global::System.Int32 _FL_DISPLAY;
        partial void OnFL_DISPLAYChanging(global::System.Int32 value);
        partial void OnFL_DISPLAYChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DOPUSK
        {
            get
            {
                return _DOPUSK;
            }
            set
            {
                OnDOPUSKChanging(value);
                ReportPropertyChanging("DOPUSK");
                _DOPUSK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOPUSK");
                OnDOPUSKChanged();
            }
        }
        private Nullable<global::System.Int32> _DOPUSK;
        partial void OnDOPUSKChanging(Nullable<global::System.Int32> value);
        partial void OnDOPUSKChanged();

        #endregion

    
    }

    #endregion

    
}
